### ISSUE TITLE
1-click-pin-experiment hasn't ended yet and shows theme data labeled as default

### ISSUE THREAD

**Issue by Mardak** [mozilla/jetstream-config#104]
https://experimenter.services.mozilla.com/nimbus/1-click-pin-experiment does indeed have 2 week enrollment and 4 week total duration but I believe it was intended as 4 weeks of observation, so that's why the experiment hasn't been ended yet.

https://github.com/mozilla/jetstream-config/blob/ad4bad757469111d8f3aac39d867dce93ebe15ef/1-click-pin-experiment.toml#L6

Also, in the nimbus results page, I noticed it showing large changes to "Set to Default" but the numbers were actually from themes:
https://github.com/mozilla/jetstream-config/blob/ad4bad757469111d8f3aac39d867dce93ebe15ef/1-click-pin-experiment.toml#L121-L125

**Comment by tdsmith** [comment]
I believe we discussed this on Slack; please raise the issue again there if I'm wrong.
